In [1]:
# Here we will see
    # How to generate random numbers
    # Stores those numbers in a text file
    # Convert random numbers into a dataframe
    # Store the dataframe values in a CSV file

In [2]:
import numpy as np

In [3]:
#RANDOM.NORMAL()
    # Can Generate Data using random.normal()
    # First Parameter : Mean
    # Second Parameter : Standard Deviation
    # Third Parameter : Number of samples

height=np.round(np.random.normal(2.5,.25,30),2) # Mean: 2.5, Std dev:.25, Number samples generated:30
height 

array([2.07, 2.67, 2.22, 2.63, 2.41, 2.19, 2.86, 2.45, 2.39, 2.43, 2.18,
       2.46, 2.92, 2.63, 2.67, 2.24, 2.42, 2.47, 2.56, 2.94, 2.35, 2.59,
       2.18, 2.59, 2.25, 2.61, 2.21, 2.67, 2.75, 2.65])

In [4]:
# Verifying the mean with the samples generated. 
np.round(np.mean(height),2)

2.49

In [5]:
weight=np.round(np.random.normal(50.5,4.25,30),2) # Mean: 3.5, Std dev:1.25, Number samples generated:30
weight 

array([49.58, 48.99, 42.52, 60.61, 49.  , 53.81, 52.6 , 57.02, 47.48,
       63.28, 43.8 , 54.23, 52.66, 50.32, 52.19, 52.56, 44.31, 43.91,
       53.07, 47.33, 51.61, 46.88, 50.03, 56.61, 59.18, 47.59, 44.28,
       51.77, 43.98, 49.61])

In [6]:
# putting together the two generated sets  together
people=np.column_stack((height,weight))
people

array([[ 2.07, 49.58],
       [ 2.67, 48.99],
       [ 2.22, 42.52],
       [ 2.63, 60.61],
       [ 2.41, 49.  ],
       [ 2.19, 53.81],
       [ 2.86, 52.6 ],
       [ 2.45, 57.02],
       [ 2.39, 47.48],
       [ 2.43, 63.28],
       [ 2.18, 43.8 ],
       [ 2.46, 54.23],
       [ 2.92, 52.66],
       [ 2.63, 50.32],
       [ 2.67, 52.19],
       [ 2.24, 52.56],
       [ 2.42, 44.31],
       [ 2.47, 43.91],
       [ 2.56, 53.07],
       [ 2.94, 47.33],
       [ 2.35, 51.61],
       [ 2.59, 46.88],
       [ 2.18, 50.03],
       [ 2.59, 56.61],
       [ 2.25, 59.18],
       [ 2.61, 47.59],
       [ 2.21, 44.28],
       [ 2.67, 51.77],
       [ 2.75, 43.98],
       [ 2.65, 49.61]])

In [7]:
# Saving randomly generated data 'people' to a text file
np.savetxt('People.txt',people) # Copy file path here

In [8]:
import pandas as pd


In [9]:
# Convert 'people' to a dataframe
df=pd.DataFrame(people)
df.head()

0      1
0  2.07  49.58
1  2.67  48.99
2  2.22  42.52
3  2.63  60.61
4  2.41  49.00

In [10]:
#Storing dataframe to CSV
df.to_csv("/People.csv") # Copy filepath here