In [2]:
#NUMPY
    #Numpy is a library for scientific computing.
    # Faster and requires less memory.
import numpy as np

In [3]:
t=np.array([[1,2,3],[4,5,6],[7,8,9],[0,3,2]]) # 2-dimensional numpy array t
t

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 3, 2]])

In [4]:
# Getting dimension of the array
t.ndim

2

In [5]:
# Getting the number of rows and number of elements in each row
t.shape

(4, 3)

In [6]:
#Total number of elements
t.size

12

In [7]:
#Accessing the elements
t[0][0] # First element in first row

1

In [8]:
#Accessing the elements
t[1][2] # Third element in second row

6

In [9]:
#Slicing
t[0,0:2] # First 2 columns in first row

array([1, 2])

In [10]:
#Slicing
t[0:2,0] # First column in first two rows

array([1, 4])

In [11]:
# Addition of 2 D Arrays
    #Similar to matrix addition
a=np.array([[1,2,3],[5,3,2]])
b=np.array([[0,1,2],[1,3,4]])
c=a+b
print('a=',a)
print('\nb=',b)
print('\nSum a+b=',c)


a= [[1 2 3]
 [5 3 2]]

b= [[0 1 2]
 [1 3 4]]

Sum a+b= [[1 3 5]
 [6 6 6]]


In [12]:
#Multiplication by a scalar
    # Each element of the array is multiplied by the scalar
    # Result is the array with same size.
d=np.array([[1,3,2],[4,5,6]])
e=2*d
print('d=',d)
print('\n2*d=',e)

d= [[1 3 2]
 [4 5 6]]

2*d= [[ 2  6  4]
 [ 8 10 12]]


In [13]:
#Hadamard product
    # Multiplying each element in the same position of both matrices
a=np.array([[1,2,3],[5,3,2]])
b=np.array([[0,1,2],[1,3,4]])
c=a*b
print('a=',a)
print('\nb=',b)
print('\nHadamard Product a*b=',c)

a= [[1 2 3]
 [5 3 2]]

b= [[0 1 2]
 [1 3 4]]

Hadamard Product a*b= [[0 2 6]
 [5 9 8]]


In [14]:
# Matrix Multiplication
    # Number of columns in the first matrix should be equal to number of rows in the second matrix.
    # m*n matrix multiplied by n*p matrix. 
a=np.array([[1,2,3],[5,3,2]]) # 2*3 matrix
b=np.array([[0,1],[1,3],[4,5]]) # 3*2 matrix
c=np.dot(a,b)
print('a=',a)
print('\nb=',b)
print('\n Product of a and b=',c)

a= [[1 2 3]
 [5 3 2]]

b= [[0 1]
 [1 3]
 [4 5]]

 Product of a and b= [[14 22]
 [11 24]]
